// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7X2GPftfksp0AyDEbUgRaoPL0mHE01HU',
    appId: '1:898998440746:web:f673efc51f7719ecc44453',
    messagingSenderId: '898998440746',
    projectId: 'shoesly-103de',
    authDomain: 'shoesly-103de.firebaseapp.com',
    storageBucket: 'shoesly-103de.appspot.com',
    measurementId: 'G-L0R2J54MLS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4xekBsYLa-zf6dhMhtwF86UY6bAlhPus',
    appId: '1:898998440746:android:ab1073bad4a4df3fc44453',
    messagingSenderId: '898998440746',
    projectId: 'shoesly-103de',
    storageBucket: 'shoesly-103de.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNar-y76zM3tM2YA1JchIGLc1ZpCnQHMc',
    appId: '1:898998440746:ios:ac2c870763be18e7c44453',
    messagingSenderId: '898998440746',
    projectId: 'shoesly-103de',
    storageBucket: 'shoesly-103de.appspot.com',
    iosBundleId: 'com.example.shoesly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNar-y76zM3tM2YA1JchIGLc1ZpCnQHMc',
    appId: '1:898998440746:ios:ac2c870763be18e7c44453',
    messagingSenderId: '898998440746',
    projectId: 'shoesly-103de',
    storageBucket: 'shoesly-103de.appspot.com',
    iosBundleId: 'com.example.shoesly',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7X2GPftfksp0AyDEbUgRaoPL0mHE01HU',
    appId: '1:898998440746:web:9b1de3e09cb15ccdc44453',
    messagingSenderId: '898998440746',
    projectId: 'shoesly-103de',
    authDomain: 'shoesly-103de.firebaseapp.com',
    storageBucket: 'shoesly-103de.appspot.com',
    measurementId: 'G-ESH1M6T20W',
  );
}
